#!/bin/bash
src_lang=ta
tgt_lang=te
src_file="./data/main/ta-te.romanized/pm_india/test".ta-te.$src_lang
model_path="dumped/main/xlm_ta-te_unsupervised/romanized/best-valid_ta-te_mt_bleu.pth"
exp_name="main/xlm_ta-te_unsupervised/romanized/$src_lang-$tgt_lang.sacrebleu"
exp_id=5k
hyp_file=./dumped/$exp_name/$exp_id/$src_lang-$tgt_lang.$tgt_lang
ref_file_orig="./data/main/ta-te.romanized/pm_india/test".ta-te.$tgt_lang
INDICNLP=./tools/indic_nlp_library
DETOKENIZE_INDIC=$INDICNLP/src/indicnlp/tokenize/indic_detokenize.py
TOKENIZE_INDIC=./indic_tok.py
MOSES=./tools/mosesdecoder/scripts
DIR=./dumped/$exp_name/$exp_id
ref_file=$DIR/ref.$tgt_lang
deromanize=true
mkdir -p $DIR
cp $ref_file_orig $ref_file
cat $src_file | python translate.py --exp_name $exp_name --exp_id $exp_id --src_lang $src_lang --tgt_lang $tgt_lang --model_path $model_path --output_path $hyp_file
sed -i 's/@@ //g' $hyp_file
sed -i 's/@@ //g' $ref_file

function indicdetokenize() {
        lg=$1
        echo detokenizing data with $DETOKENIZE_INDIC for $lg
        python "$DETOKENIZE_INDIC" $DIR/hypothesis.derom.$tgt_lang ./dumped/$exp_name/$exp_id/hypothesis.$tgt_lang $lg
	python "$DETOKENIZE_INDIC" $DIR/reference.derom.$tgt_lang ./dumped/$exp_name/$exp_id/reference.$tgt_lang $lg
}

function mosesdetokenize(){
	lg=en
      	if [ ! -d "$MOSES" ]; then
                cd "tools/"
                git clone https://github.com/moses-smt/mosesdecoder.git
                cd ../
        fi
        tools/mosesdecoder/scripts/tokenizer/detokenizer.perl -l $lg < $DIR/hypothesis.derom.$tgt_lang > ./dumped/$exp_name/$exp_id/hypothesis.$tgt_lang
	tools/mosesdecoder/scripts/tokenizer/detokenizer.perl -l $lg < $DIR/reference.derom.$tgt_lang > ./dumped/$exp_name/$exp_id/reference.$tgt_lang
}
if [ "$deromanize" = "true" ]; then
	echo "deromanizing"
	python "$TOKENIZE_INDIC" --indic_nlp_path "$INDICNLP" --language "$tgt_lang" --input "$hyp_file" --output "$DIR/hypothesis.derom.$tgt_lang"  --evalmode true --deromanize true
	python "$TOKENIZE_INDIC" --indic_nlp_path "$INDICNLP" --language "$tgt_lang" --input "$ref_file" --output "$DIR/reference.derom.$tgt_lang" --evalmode true --deromanize true
else
	echo "Not deromanizing"
        python "$TOKENIZE_INDIC" --indic_nlp_path "$INDICNLP" --language "$tgt_lang" --input "$hyp_file" --output "$DIR/hypothesis.derom.$tgt_lang"  --evalmode true 
        python "$TOKENIZE_INDIC" --indic_nlp_path "$INDICNLP" --language "$tgt_lang" --input "$ref_file" --output "$DIR/reference.derom.$tgt_lang" --evalmode true 
fi
if [ $tgt_lang != "en" ]; then
        indicdetokenize $tgt_lang
else
	mosesdetokenize
fi
#dos2unix $DIR/hypothesis.$tgt_lang
#dos2unix $DIR/reference.$tgt_lang 
python evalbleu.py --hyp ./dumped/$exp_name/$exp_id/hypothesis.$tgt_lang --ref ./dumped/$exp_name/$exp_id/reference.$tgt_lang 

